# If you would like to change the commands to something else, this can be done in the commands.yml file.
# View this page for help on adding command aliases: http://wiki.bukkit.org/Commands.yml
name: ExamplePlugin
description: A description for your plugin will go here. No quotes needed.
main: de.bmarwell.bukkit.ExamplePlugin
version: 0.0.1-SNAPSHOT
author: Benjamin Marwell
website: github.com/bmhm/bukkit-plugin-example
depend:
  - ProtocolLib